# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Deploy

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    # Any prerequisite steps
    - uses: actions/checkout@v2

    # Deploy to local repo
    - name: Deploy
      uses: actions/checkout@v2
      env:
        REPO: self
        BRANCH: deployment
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "This updates the content to the commit {sha} that had the message:\n{msg} to {target-branch}"